=== wenqizheng326/database_setup/FAIRtrain-schema_2/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "TensileTestData",
  "type": "object",
  "properties": {
    "sample_id": { "type": "string" },
    "width": { "type": "number" },
    "thickness": { "type": "number" },
    "length": { "type": "number" },
    "data": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "mm": { "type": "number" },
          "N": { "type": "number" }
        },
        "required": ["mm", "N"]
      }
    },
    "extracted_properties": {
      "type": "object",
      "properties": {
        "youngs_modulus": { "type": "number" },
        "ultimate_tensile_strength": { "type": "number" }
      },
      "required": ["youngs_modulus", "ultimate_tensile_strength"]
    }
  },
  "required": ["sample_id", "width", "thickness", "length", "data", "extracted_properties"]
}

=== wenqizheng326/database_setup/FAIRtrain-schema_2/dictionary/groupB_test_13.json
{
    "sample_id": "groupB_test_13",
    "width": 5.32,
    "thickness": 3.6,
    "length": 25.0,
    "data": [
        {
            "mm": 1.1771917e-06,
            "N": 0.72834444
        },
        {
            "mm": 0.0021871625999999,
            "N": 1.1430656
        },
        {
            "mm": 0.0046683848,
            "N": 1.4529223
        },
        {
            "mm": 0.0071715265999999,
            "N": 1.6180464
        },
        {
            "mm": 0.0096780956,
            "N": 2.0762117
        },
        {
            "mm": 0.012194678,
            "N": 2.1859231
        },
        {
            "mm": 0.014694989,
            "N": 2.4418932
        },
        {
            "mm": 0.017206714,
            "N": 2.8396443
        },
        {
            "mm": 0.019685358,
            "N": 3.1444543
        },
        {
            "mm": 0.022185728,
            "N": 3.429785
        },
        {
            "mm": 0.024667189,
            "N": 3.8495247
        },
        {
            "mm": 0.027153909,
            "N": 4.0062609
        },
        {
            "mm": 0.029650897,
            "N": 4.3466637
        },
        {
            "mm": 0.032157421,
            "N": 4.7772008
        },
        {
            "mm": 0.034665823,
            "N": 4.88699
        },
        {
            "mm": 0.037185594,
            "N": 5.2738447
        },
        {
            "mm": 0.039694399,
            "N": 5.5644302
        },
        {
            "mm": 0.0421910879999999,
            "N": 5.8739604
        },
        {
            "mm": 0.044684455,
            "N": 6.0540736
        },
        {
            "mm": 0.047178105,
            "N": 6.3881808
        },
        {
            "mm": 0.049664959,
            "N": 6.6194042
        },
        {
            "mm": 0.052160591,
            "N": 6.9153478
        },
        {
            "mm": 0.054685131,
            "N": 7.2102807
        },
        {
            "mm": 0.057171747,
            "N": 7.6080897
        },
        {
            "mm": 0.059694275,
            "N": 7.7917639
        },
        {
            "mm": 0.062213764,
            "N": 8.1721892
        },
        {
            "mm": 0.06470342,
            "N": 8.3585966
        },
        {
            "mm": 0.067193195,
            "N": 8.5023689
        },
        {
            "mm": 0.069674775,
            "N": 8.8002968
        },
        {
            "mm": 0.072173342,
            "N": 9.0926228
        },
        {
            "mm": 0.07465817,
            "N": 9.3726847
        },
        {
            "mm": 0.077172101,
            "N": 9.5904146
        },
        {
            "mm": 0.079672456,
            "N": 9.9487317
        },
        {
            "mm": 0.082185552,
            "N": 10.012824
        },
        {
            "mm": 0.084674969,
            "N": 10.237904
        },
        {
            "mm": 0.087197751,
            "N": 10.516797
        },
        {
            "mm": 0.0896947229999999,
            "N": 10.776128
        },
        {
            "mm": 0.092179939,
            "N": 11.219695
        },
        {
            "mm": 0.0946962089999999,
            "N": 11.431761
        },
        {
            "mm": 0.0971738249999999,
            "N": 11.52889
        },
        {
            "mm": 0.099683061,
            "N": 11.829124
        },
        {
            "mm": 0.10217644,
            "N": 12.012508
        },
        {
            "mm": 0.10467805,
            "N": 12.47049
        },
        {
            "mm": 0.10718827,
            "N": 12.516972
        },
        {
            "mm": 0.10969405,
            "N": 12.951953
        },
        {
            "mm": 0.11219512,
            "N": 13.140294
        },
        {
            "mm": 0.11469823,
            "N": 13.420104
        },
        {
            "mm": 0.11719504,
            "N": 13.74407
        },
        {
            "mm": 0.11966728,
            "N": 13.895549
        },
        {
            "mm": 0.12216662,
            "N": 14.227602
        },
        {
            "mm": 0.1246698499999999,
            "N": 14.697084
        },
        {
            "mm": 0.12717073,
            "N": 15.054308
        },
        {
            "mm": 0.12967427,
            "N": 15.158028
        },
        {
            "mm": 0.13218032,
            "N": 15.446763
        },
        {
            "mm": 0.134699,
            "N": 16.026277
        },
        {
            "mm": 0.137201,
            "N": 16.366354
        },
        {
            "mm": 0.1396871499999999,
            "N": 16.655753
        },
        {
            "mm": 0.14217868,
            "N": 17.117531
        },
        {
            "mm": 0.14468005,
            "N": 17.23759
        },
        {
            "mm": 0.14715946,
            "N": 17.879193
        },
        {
            "mm": 0.14967544,
            "N": 18.042086
        },
        {
            "mm": 0.1521752599999999,
            "N": 18.4649
        },
        {
            "mm": 0.15468994,
            "N": 18.747815
        },
        {
            "mm": 0.15720132,
            "N": 19.197525
        },
        {
            "mm": 0.15970117,
            "N": 19.65409
        },
        {
            "mm": 0.16220278,
            "N": 19.853104
        },
        {
            "mm": 0.16469383,
            "N": 20.246283
        },
        {
            "mm": 0.1671750799999999,
            "N": 20.61751
        },
        {
            "mm": 0.16967474,
            "N": 20.770498
        },
        {
            "mm": 0.1721577,
            "N": 21.300731
        },
        {
            "mm": 0.17467032,
            "N": 21.494239
        },
        {
            "mm": 0.17718834,
            "N": 22.082693
        },
        {
            "mm": 0.17968777,
            "N": 22.477878
        },
        {
            "mm": 0.18218789,
            "N": 22.782571
        },
        {
            "mm": 0.18469238,
            "N": 22.998396
        },
        {
            "mm": 0.18719965,
            "N": 23.482933
        },
        {
            "mm": 0.18968573,
            "N": 23.865283
        },
        {
            "mm": 0.1921695199999999,
            "N": 24.104691
        },
        {
            "mm": 0.19466613,
            "N": 24.327041
        },
        {
            "mm": 0.19715862,
            "N": 24.804422
        },
        {
            "mm": 0.19967109,
            "N": 25.112898
        },
        {
            "mm": 0.20218347,
            "N": 25.559069
        },
        {
            "mm": 0.20468654,
            "N": 25.830978
        },
        {
            "mm": 0.207193,
            "N": 26.237552
        },
        {
            "mm": 0.20970023,
            "N": 26.467992
        },
        {
            "mm": 0.21217741,
            "N": 26.950786
        },
        {
            "mm": 0.21466555,
            "N": 27.070504
        },
        {
            "mm": 0.21715882,
            "N": 27.359234
        },
        {
            "mm": 0.21965989,
            "N": 27.593511
        },
        {
            "mm": 0.2221587,
            "N": 28.142214
        },
        {
            "mm": 0.22467531,
            "N": 28.425436
        },
        {
            "mm": 0.2271867799999999,
            "N": 28.729438
        },
        {
            "mm": 0.22969426,
            "N": 29.060868
        },
        {
            "mm": 0.2321853499999999,
            "N": 29.200352
        },
        {
            "mm": 0.23468381,
            "N": 29.792191
        },
        {
            "mm": 0.23717538,
            "N": 30.000174
        },
        {
            "mm": 0.23969513,
            "N": 30.349409
        },
        {
            "mm": 0.24217416,
            "N": 30.550192
        },
        {
            "mm": 0.2446745899999999,
            "N": 30.911166
        },
        {
            "mm": 0.24718279,
            "N": 31.254191
        },
        {
            "mm": 0.24967936,
            "N": 31.586522
        },
        {
            "mm": 0.25219016,
            "N": 32.047361
        },
        {
            "mm": 0.25469626,
            "N": 32.343197
        },
        {
            "mm": 0.25718905,
            "N": 32.627042
        },
        {
            "mm": 0.25969239,
            "N": 32.894815
        },
        {
            "mm": 0.26217614,
            "N": 33.240436
        },
        {
            "mm": 0.26466352,
            "N": 33.652047
        },
        {
            "mm": 0.26716015,
            "N": 33.972204
        },
        {
            "mm": 0.26966408,
            "N": 34.138555
        },
        {
            "mm": 0.27217075,
            "N": 34.63263
        },
        {
            "mm": 0.27468327,
            "N": 34.836596
        },
        {
            "mm": 0.27718343,
            "N": 35.194458
        },
        {
            "mm": 0.2796930099999999,
            "N": 35.34414
        },
        {
            "mm": 0.28218549,
            "N": 35.610106
        },
        {
            "mm": 0.28468159,
            "N": 35.99186
        },
        {
            "mm": 0.28716859,
            "N": 36.082459
        },
        {
            "mm": 0.2896705,
            "N": 36.623294
        },
        {
            "mm": 0.29216903,
            "N": 36.975739
        },
        {
            "mm": 0.29467918,
            "N": 37.243386
